import json
import re
from tutor.models import SPECS


def dot(diagram):
    lines = ['digraph Topic {', 'rankdir=TB;', 'node [shape=box, style="rounded,filled", fillcolor="#e8f1ff"];']
    for node in diagram['nodes']:
        lines.append(f'{json.dumps(node["id"])} [label={json.dumps(node["label"], ensure_ascii=False)}];')
    for edge in diagram['edges']:
        lines.append(f'{json.dumps(edge["source"])} -> {json.dumps(edge["target"])} [label={json.dumps(edge.get("label", ""), ensure_ascii=False)}];')
    return '\n'.join(lines + ['}'])


def bullets(values, numbered=False):
    return '\n'.join(f'{i}. {v}' if numbered else f'- {v}' for i, v in enumerate(values, 1))


def section_markdown(key, data):
    if key == 'architecture':
        return data['overview'] + '\n\n**Components**\n\n' + bullets(data['components']) + '\n\n**Flow**\n\n' + bullets(data['steps'], True)
    if key == 'professional':
        return data['explanation'] + '\n\n' + bullets(data['key_points']) + '\n\n**Pitfalls**\n\n' + bullets(data['pitfalls'])
    if key == 'layman':
        return data['analogy'] + '\n\n' + bullets(data['mapping']) + '\n\n**Where the analogy stops:** ' + data['limits_of_analogy']
    if key == 'comparison':
        def cell(value):
            return value.replace('|', '\\|').replace('\n', ' ')
        return '| Related topic | Similarity | Difference | When to choose |\n|---|---|---|---|\n' + '\n'.join('| ' + ' | '.join(cell(row[k]) for k in ('related_topic', 'similarity', 'difference', 'when_to_choose')) + ' |' for row in data['rows'])
    if key == 'examples':
        parts = []
        for i, example in enumerate(data['examples'], 1):
            part = f'### Example {i}: {example["title"]}\n\n{example["scenario"]}\n\n' + bullets(example['walkthrough'], True) + '\n\n**Expected result:** ' + example['expected_result']
            if example['code']:
                fence = '`' * max(3, max((len(s) for s in re.findall(r'`+', example['code'])), default=0) + 1)
                language = re.sub(r'[^a-zA-Z0-9_+-]', '', example['code_language'])
                part += f'\n\n{fence}{language}\n{example["code"]}\n{fence}'
            parts.append(part)
        return '\n\n'.join(parts)
    if key == 'end_to_end':
        return '\n\n'.join('**' + title + '**\n\n' + bullets(data[field], field == 'steps') for title, field in [('Prerequisites','prerequisites'), ('Full flow','steps'), ('Failure handling','failure_handling'), ('Verification','verification')])
    return ' '.join(data['sentences'])


def _strip_markdown(text):
    text = re.sub(r'^#{1,6}\s*', '', text, flags=re.M)
    text = re.sub(r'\*\*(.*?)\*\*', r'\1', text)
    text = re.sub(r'\*(.*?)\*', r'\1', text)
    text = re.sub(r'`([^`]*)`', r'\1', text)
    text = re.sub(r'\[(.*?)\]\((.*?)\)', r'\1', text)
    text = re.sub(r'^\s*[-*+]\s*', '', text, flags=re.M)
    text = re.sub(r'^\s*\d+\.\s*', '', text, flags=re.M)
    return text.strip()


def export_markdown(topic, sections):
    parts = [f'# {topic}', 'Generated by Gemini. Educational output; verify factual and version-specific claims.']
    for i, (key, title, _, _) in enumerate(SPECS, 1):
        if key in sections:
            parts.append(f'## {i}. {title}\n\n' + section_markdown(key, sections[key]))
            if 'diagram' in sections[key]:
                parts.append('```dot\n' + dot(sections[key]['diagram']) + '\n```')
    return '\n\n'.join(parts)


def export_pdf(topic, sections):
    from fpdf import FPDF

    pdf = FPDF()
    pdf.set_auto_page_break(auto=True, margin=15)
    pdf.add_page()
    page_width = pdf.epw

    pdf.set_font('Helvetica', 'B', 18)
    pdf.multi_cell(page_width, 10, topic)
    pdf.set_font('Helvetica', '', 10)
    pdf.multi_cell(page_width, 7, 'Generated by Gemini. Educational output; verify factual and version-specific claims.')

    for i, (key, title, _, _) in enumerate(SPECS, 1):
        if key not in sections:
            continue

        pdf.ln(2)
        pdf.set_font('Helvetica', 'B', 13)
        pdf.multi_cell(page_width, 8, f'{i}. {title}')
        pdf.set_font('Helvetica', '', 10)

        text = section_markdown(key, sections[key])
        for chunk in re.split(r'\n\s*\n', text):
            clean = _strip_markdown(chunk)
            if not clean:
                continue
            pdf.multi_cell(page_width, 6, clean)
            pdf.ln(1)

        if 'diagram' in sections[key]:
            pdf.multi_cell(page_width, 6, 'Diagram DOT:')
            pdf.multi_cell(page_width, 6, dot(sections[key]['diagram']))
            pdf.ln(1)

    return bytes(pdf.output())
